"""Sittings read model: the API is served from Postgres, external services only fill what is missing.

- sitting list: pulled from the Sejm API once, when the table is empty; never refreshed
- sitting descriptions: generated by Gemini from the agenda and stored, only for the sittings
  a request actually returns (the free tier allows a handful of calls per minute); rows still
  missing one (no API key at the time, Gemini error) are retried on later requests
"""

import asyncio
import logging
import math
from collections import Counter, defaultdict
from collections.abc import Iterable
from datetime import UTC, date, datetime, timedelta

from bs4 import BeautifulSoup
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.models import Sitting
from app.schemas.sittings import Page, SittingListItem
from app.services.sejm_client import SejmClient
from app.utils.gemini_client import GeminiError, get_gemini_client, retry_after
from app.utils.gemini_client.tasks import SittingSummary, summarize_sitting

logger = logging.getLogger(__name__)

SUMMARY_RETRY_AFTER = timedelta(minutes=10)
GEMINI_CONCURRENCY = 5

# One sync per term at a time; enough for a single-process deployment.
_locks: defaultdict[int, asyncio.Lock] = defaultdict(asyncio.Lock)
_summaries_paused_until = datetime.min.replace(tzinfo=UTC)


def agenda_text(html: str | None) -> str | None:
    """Agenda HTML from the Sejm API -> one agenda point per line; None when there are no points."""
    if not html:
        return None
    points = [" ".join(li.get_text().split()) for li in BeautifulSoup(html, "lxml").find_all("li")]
    return "\n".join(point for point in points if point) or None


async def list_sittings(
    session: AsyncSession, sejm: SejmClient, term: int, page: int, page_size: int
) -> Page[SittingListItem]:
    async with _locks[term]:
        await _ensure_sittings(session, sejm, term)
        rows = list(
            await session.scalars(
                select(Sitting)
                .where(Sitting.term == term)
                .order_by(Sitting.number.desc())
                .limit(page_size)
                .offset((page - 1) * page_size)
            )
        )
        await _fill_descriptions(session, rows)
    total = await session.scalar(select(func.count()).select_from(Sitting).where(Sitting.term == term)) or 0
    return Page(
        items=[SittingListItem.model_validate(row) for row in rows],
        page=page,
        page_size=page_size,
        total=total,
        pages=math.ceil(total / page_size),
    )


async def _ensure_sittings(session: AsyncSession, sejm: SejmClient, term: int) -> None:
    if not await session.scalar(select(func.count()).select_from(Sitting).where(Sitting.term == term)):
        await _load_sittings(session, sejm, term)


def _pause_summaries(exc: BaseException) -> None:
    """Stop calling Gemini for as long as it asked us to, or SUMMARY_RETRY_AFTER when it did not say."""
    global _summaries_paused_until
    until = datetime.now(UTC) + (retry_after(exc) or SUMMARY_RETRY_AFTER)
    _summaries_paused_until = max(_summaries_paused_until, until)


async def _load_sittings(session: AsyncSession, sejm: SejmClient, term: int) -> None:
    raw, per_day = await asyncio.gather(sejm.proceedings(term), sejm.votings_per_day(term))
    votings_count: Counter[int] = Counter()
    for day in per_day:
        votings_count[day["proceeding"]] += day["votingsNum"]

    now = datetime.now(UTC)
    for item in raw:
        if not item["number"]:  # planned sittings have no number yet
            continue
        session.add(
            Sitting(
                term=term,
                number=item["number"],
                title=item["title"],
                dates=[date.fromisoformat(d) for d in item["dates"]],
                agenda=agenda_text(item.get("agenda")),
                votings_count=votings_count[item["number"]],
                synced_at=now,
            )
        )
    await session.commit()


async def _fill_descriptions(session: AsyncSession, sittings: Iterable[Sitting]) -> None:
    """Generate and store missing descriptions. Failures are not fatal: the fields stay null and are retried later."""
    pending = [s for s in sittings if s.description is None and s.agenda is not None]
    if not pending or datetime.now(UTC) < _summaries_paused_until:
        return
    try:
        gemini = get_gemini_client()
    except GeminiError as exc:
        logger.warning("Sitting descriptions disabled: %s", exc)
        _pause_summaries(exc)
        return

    semaphore = asyncio.Semaphore(GEMINI_CONCURRENCY)

    async def summarize(sitting: Sitting) -> SittingSummary:
        async with semaphore:
            return await summarize_sitting(gemini, sitting.title, sitting.agenda)

    results = await asyncio.gather(*(summarize(s) for s in pending), return_exceptions=True)
    for sitting, result in zip(pending, results, strict=True):
        if isinstance(result, BaseException):
            logger.warning("Description of sitting %s failed: %s", sitting.number, result)
            _pause_summaries(result)
            continue
        sitting.description = result.description.strip()
    await session.commit()
