"""Sittings read model: the API is served from Postgres, external services only fill what is missing.

- sitting list: pulled from the Sejm API once, when the table is empty; never refreshed
- sitting descriptions: generated by Gemini from the agenda and stored, only for the sittings
  a request actually returns (the free tier allows a handful of calls per minute); rows still
  missing one (no API key at the time, Gemini error) are retried on later requests
- votings of a sitting: pulled on first request, re-pulled every LIVE_TTL while the sitting
  is in progress, never again once it has ended (votings are immutable)
- bill summaries: generated once by Gemini and stored
"""

import asyncio
import logging
import math
import re
from collections import Counter, defaultdict
from collections.abc import Iterable
from datetime import UTC, date, datetime, timedelta
from typing import Any

import httpx
from bs4 import BeautifulSoup
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.db.models import Bill, Sitting, Voting, VotingClubResult
from app.schemas.sittings import BillOut, ClubVotes, Page, SittingDetail, SittingListItem, Votes
from app.services.sejm_client import SejmClient
from app.utils.gemini_client import GeminiError, get_gemini_client, retry_after
from app.utils.gemini_client.tasks import SittingSummary, summarize_bill, summarize_sitting

logger = logging.getLogger(__name__)

LIVE_TTL = timedelta(minutes=15)
SUMMARY_RETRY_AFTER = timedelta(minutes=1)
SEJM_CONCURRENCY = 5
GEMINI_CONCURRENCY = 5

_PRINT = re.compile(r"druk(?:i|u|ów)?\s+(?:nr\s+)?(\d+)", re.IGNORECASE)
_AGENDA_POINT = re.compile(r"^Pkt\.?\s*\d+\s*")
BILL = "projekt ustawy"
_VOTE_FIELDS = {"YES": "yes", "NO": "no", "ABSTAIN": "abstain"}

# One sync per sitting at a time (key 0 = the sitting list); enough for a single-process deployment.
_locks: defaultdict[tuple[int, int], asyncio.Lock] = defaultdict(asyncio.Lock)
_summaries_paused_until = datetime.min.replace(tzinfo=UTC)


def agenda_text(html: str | None) -> str | None:
    """Agenda HTML from the Sejm API -> one agenda point per line; None when there are no points."""
    if not html:
        return None
    points = [" ".join(li.get_text().split()) for li in BeautifulSoup(html, "lxml").find_all("li")]
    return "\n".join(point for point in points if point) or None


def print_number(voting_title: str) -> str | None:
    """'Pkt. 2 Sprawozdanie ... (druki nr 876, 984 i 984-A)' -> '876' (the print that started the process)."""
    match = _PRINT.search(voting_title)
    return match[1] if match else None


async def list_sittings(
    session: AsyncSession, sejm: SejmClient, term: int, page: int, page_size: int
) -> Page[SittingListItem]:
    async with _locks[(term, 0)]:
        await _ensure_sittings(session, sejm, term)
        rows = list(
            await session.scalars(
                select(Sitting)
                .where(Sitting.term == term)
                .order_by(Sitting.number.desc())
                .limit(page_size)
                .offset((page - 1) * page_size)
            )
        )
        await _fill_descriptions(session, rows)
    total = await session.scalar(select(func.count()).select_from(Sitting).where(Sitting.term == term)) or 0
    return Page(
        items=[SittingListItem.model_validate(row) for row in rows],
        page=page,
        page_size=page_size,
        total=total,
        pages=math.ceil(total / page_size),
    )


async def get_sitting(session: AsyncSession, sejm: SejmClient, term: int, number: int) -> SittingDetail | None:
    async with _locks[(term, 0)]:
        await _ensure_sittings(session, sejm, term)
        sitting = await session.scalar(select(Sitting).where(Sitting.term == term, Sitting.number == number))
        if sitting is None:
            return None
        await _fill_descriptions(session, [sitting])

    if _votings_stale(sitting):
        async with _locks[(term, number)]:
            await session.refresh(sitting)
            if _votings_stale(sitting):
                try:
                    await _sync_votings(session, sejm, sitting)
                except httpx.HTTPError:
                    if sitting.votings_synced_at is None:
                        raise
                    await session.rollback()
                    logger.warning("Sejm API unavailable, serving stored votings of sitting %s", number)

    sitting = await session.scalar(
        select(Sitting)
        .where(Sitting.id == sitting.id)
        .options(
            selectinload(Sitting.votings).selectinload(Voting.clubs),
            selectinload(Sitting.votings).selectinload(Voting.bill),
        )
        .execution_options(populate_existing=True)
    )
    await _fill_summaries(session, {v.bill for v in sitting.votings if v.bill})
    return _to_detail(sitting)


async def _ensure_sittings(session: AsyncSession, sejm: SejmClient, term: int) -> None:
    if not await session.scalar(select(func.count()).select_from(Sitting).where(Sitting.term == term)):
        await _load_sittings(session, sejm, term)


def _pause_summaries(exc: BaseException) -> None:
    """Stop calling Gemini for as long as it asked us to, but never longer than SUMMARY_RETRY_AFTER.

    A spent daily quota reports a retry delay of many hours; capping it keeps null texts being retried.
    """
    global _summaries_paused_until
    until = datetime.now(UTC) + min(retry_after(exc) or SUMMARY_RETRY_AFTER, SUMMARY_RETRY_AFTER)
    _summaries_paused_until = max(_summaries_paused_until, until)


async def _load_sittings(session: AsyncSession, sejm: SejmClient, term: int) -> None:
    raw, per_day = await asyncio.gather(sejm.proceedings(term), sejm.votings_per_day(term))
    votings_count: Counter[int] = Counter()
    for day in per_day:
        votings_count[day["proceeding"]] += day["votingsNum"]

    now = datetime.now(UTC)
    for item in raw:
        if not item["number"]:  # planned sittings have no number yet
            continue
        session.add(
            Sitting(
                term=term,
                number=item["number"],
                title=item["title"],
                dates=[date.fromisoformat(d) for d in item["dates"]],
                agenda=agenda_text(item.get("agenda")),
                votings_count=votings_count[item["number"]],
                synced_at=now,
            )
        )
    await session.commit()


async def _fill_descriptions(session: AsyncSession, sittings: Iterable[Sitting]) -> None:
    """Generate and store missing descriptions. Failures are not fatal: the fields stay null and are retried later."""
    pending = [s for s in sittings if s.description is None and s.agenda is not None]
    if not pending or datetime.now(UTC) < _summaries_paused_until:
        return
    try:
        gemini = get_gemini_client()
    except GeminiError as exc:
        logger.warning("Sitting descriptions disabled: %s", exc)
        _pause_summaries(exc)
        return

    semaphore = asyncio.Semaphore(GEMINI_CONCURRENCY)

    async def summarize(sitting: Sitting) -> SittingSummary:
        async with semaphore:
            return await summarize_sitting(gemini, sitting.title, sitting.agenda)

    results = await asyncio.gather(*(summarize(s) for s in pending), return_exceptions=True)
    for sitting, result in zip(pending, results, strict=True):
        if isinstance(result, BaseException):
            logger.warning("Description of sitting %s failed: %s", sitting.number, result)
            _pause_summaries(result)
            continue
        sitting.description = result.description.strip()
    await session.commit()


def _votings_stale(sitting: Sitting) -> bool:
    now = datetime.now(UTC)
    if sitting.dates[0] > now.date():
        return False  # not started yet
    if sitting.votings_synced_at is None:
        return True
    if sitting.votings_synced_at.date() > sitting.dates[-1]:
        return False  # synced after the sitting ended
    return now - sitting.votings_synced_at > LIVE_TTL


async def _sync_votings(session: AsyncSession, sejm: SejmClient, sitting: Sitting) -> None:
    listing = await sejm.votings(sitting.term, sitting.number)
    known = set(await session.scalars(select(Voting.number).where(Voting.sitting_id == sitting.id)))
    missing = [v["votingNumber"] for v in listing if v["votingNumber"] not in known]

    semaphore = asyncio.Semaphore(SEJM_CONCURRENCY)

    async def fetch(number: int) -> dict[str, Any]:
        async with semaphore:
            return await sejm.voting(sitting.term, sitting.number, number)

    details = await asyncio.gather(*(fetch(number) for number in missing))

    titles = {p: _AGENDA_POINT.sub("", d["title"]) for d in details if (p := print_number(d["title"]))}
    bills = await _ensure_bills(session, sejm, sitting.term, titles)
    for raw in details:
        session.add(_build_voting(sitting, raw, bills.get(print_number(raw["title"]))))
    sitting.votings_synced_at = datetime.now(UTC)
    await session.commit()


async def _ensure_bills(
    session: AsyncSession, sejm: SejmClient, term: int, fallback_titles: dict[str, str]
) -> dict[str, Bill]:
    """Return bills for the given print numbers, creating the ones we have not seen yet."""
    if not fallback_titles:
        return {}
    bills = {
        b.print_number: b
        for b in await session.scalars(
            select(Bill).where(Bill.term == term, Bill.print_number.in_(fallback_titles.keys()))
        )
    }
    missing = [p for p in fallback_titles if p not in bills]
    semaphore = asyncio.Semaphore(SEJM_CONCURRENCY)

    async def fetch(number: str) -> dict[str, Any] | None:
        async with semaphore:
            return await sejm.process(term, number)

    for number, process in zip(missing, await asyncio.gather(*(fetch(p) for p in missing)), strict=True):
        process = process or {}
        links = {link["rel"]: link["href"] for link in process.get("links", [])}
        bill = Bill(
            term=term,
            print_number=number,
            title=process.get("title") or fallback_titles[number],
            document_type=process.get("documentType"),
            description=process.get("description"),
            eli=process.get("ELI"),
            isap_url=links.get("isap"),
        )
        session.add(bill)
        bills[number] = bill
    return bills


def _build_voting(sitting: Sitting, raw: dict[str, Any], bill: Bill | None) -> Voting:
    topic, description = raw.get("topic"), raw.get("description")
    voting = Voting(
        sitting=sitting,
        bill=bill,
        number=raw["votingNumber"],
        held_at=datetime.fromisoformat(raw["date"]),
        kind=raw["kind"],
        title=raw["title"],
        topic=topic,
        description=description,
        is_final="całość projektu" in (description or "") or "nad całością" in (topic or ""),
        yes=raw["yes"],
        no=raw["no"],
        abstain=raw["abstain"],
        not_participating=raw["notParticipating"],
        majority_votes=raw.get("majorityVotes", 0),
    )
    if raw["kind"] == "ELECTRONIC":
        per_club: defaultdict[str, Counter[str]] = defaultdict(Counter)
        for vote in raw.get("votes", []):
            per_club[vote["club"]][_VOTE_FIELDS.get(vote["vote"], "absent")] += 1
        voting.clubs = [VotingClubResult(club=club, **counts) for club, counts in per_club.items()]
    return voting


async def _fill_summaries(session: AsyncSession, bills: Iterable[Bill]) -> None:
    """Generate and store missing summaries. Failures are not fatal: the summary stays null and is retried later."""
    pending = [b for b in bills if b.summary is None and b.document_type == BILL]
    if not pending or datetime.now(UTC) < _summaries_paused_until:
        return
    try:
        gemini = get_gemini_client()
    except GeminiError as exc:
        logger.warning("Bill summaries disabled: %s", exc)
        _pause_summaries(exc)
        return

    semaphore = asyncio.Semaphore(GEMINI_CONCURRENCY)

    async def summarize(bill: Bill) -> str:
        async with semaphore:
            return await summarize_bill(gemini, bill.title, bill.description)

    results = await asyncio.gather(*(summarize(b) for b in pending), return_exceptions=True)
    for bill, result in zip(pending, results, strict=True):
        if isinstance(result, BaseException):
            logger.warning("Summary for print %s failed: %s", bill.print_number, result)
            _pause_summaries(result)
            continue
        bill.summary = result
        bill.summary_model = gemini.model
    await session.commit()


def _to_detail(sitting: Sitting) -> SittingDetail:
    by_bill: dict[int, list[Voting]] = defaultdict(list)
    for voting in sitting.votings:
        if voting.bill and voting.bill.document_type == BILL:
            by_bill[voting.bill_id].append(voting)

    turnouts = [v.turnout for v in sitting.votings]
    return SittingDetail(
        **SittingListItem.model_validate(sitting).model_dump(),
        turnout=round(sum(turnouts) / len(turnouts), 4) if turnouts else None,
        source_url=sitting.source_url,
        bills=[_to_bill(votings) for votings in by_bill.values()],
    )


def _to_bill(votings: list[Voting]) -> BillOut:
    bill = votings[0].bill
    # Only the vote on the whole bill decides; amendments and motions are skipped.
    final = next((v for v in reversed(votings) if v.is_final and v.passed is not None), None)
    out = BillOut(
        print_number=bill.print_number,
        title=bill.title,
        summary=bill.summary,
        result="pending",
        votes=None,
        turnout=None,
        clubs=None,
        source_url=bill.source_url,
    )
    if final:
        out.result = "passed" if final.passed else "rejected"
        out.votes = Votes(yes=final.yes, no=final.no, abstain=final.abstain, absent=final.not_participating)
        out.turnout = final.turnout
        out.clubs = [ClubVotes.model_validate(club) for club in final.clubs]
    return out
