import enum
from datetime import date, datetime
from typing import Any

from sqlalchemy import Date, DateTime, Enum, ForeignKey, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Act(Base):
    __tablename__ = "acts"

    id: Mapped[int] = mapped_column(primary_key=True)
    # Slug prefix of the act's articles, see app.pipeline.act_keys: "ustawa_o_podatku_akcyzowym_2008_12_06"
    act_key: Mapped[str] = mapped_column(String(255), unique=True)
    eli: Mapped[str | None] = mapped_column(String(64), unique=True)  # e.g. "DU/2024/1539"
    act_type: Mapped[str | None] = mapped_column(String(64))  # "ustawa", "rozporządzenie", ...
    act_date: Mapped[date | None] = mapped_column(Date)
    title: Mapped[str] = mapped_column(Text)  # full official title
    short_title: Mapped[str | None] = mapped_column(Text)  # e.g. "Kodeks karny"

    articles: Mapped[list["Article"]] = relationship(back_populates="act", cascade="all, delete-orphan")


class Article(Base):
    __tablename__ = "articles"
    __table_args__ = (UniqueConstraint("act_id", "number"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    act_id: Mapped[int] = mapped_column(ForeignKey("acts.id", ondelete="CASCADE"))
    number: Mapped[str] = mapped_column(String(32))
    # The only lookup key for articles: "ustawa_o_podatku_akcyzowym_2008_12_06_art_99b"
    slug: Mapped[str] = mapped_column(String(300), unique=True, index=True)
    position: Mapped[int] = mapped_column(Integer)  # order within the act
    text: Mapped[str] = mapped_column(Text)
    summary: Mapped[str | None] = mapped_column(Text)
    # References found by the LLM, with resolution result: [{"act_key", "article", "resolved"}]
    references: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, default=list)

    act: Mapped[Act] = relationship(back_populates="articles")


class Sitting(Base):
    """Sejm sitting (posiedzenie), mirrored from /proceedings."""

    __tablename__ = "sittings"
    __table_args__ = (UniqueConstraint("term", "number"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    term: Mapped[int]
    number: Mapped[int]
    title: Mapped[str] = mapped_column(Text)
    dates: Mapped[list[date]] = mapped_column(ARRAY(Date))
    agenda: Mapped[str | None] = mapped_column(Text)  # plain-text agenda points; input for the Gemini summary
    description: Mapped[str | None] = mapped_column(Text)  # 2 sentences generated by Gemini from the agenda
    votings_count: Mapped[int] = mapped_column(default=0)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    # None until the votings of this sitting were pulled for the first time
    votings_synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    votings: Mapped[list["Voting"]] = relationship(back_populates="sitting", order_by="Voting.number")

    @property
    def start_date(self) -> date:
        return self.dates[0]

    @property
    def end_date(self) -> date:
        return self.dates[-1]

    @property
    def status(self) -> str:
        today = date.today()
        if self.dates[0] > today:
            return "planned"
        return "finished" if self.dates[-1] < today else "in_progress"

    @property
    def source_url(self) -> str:
        return f"https://api.sejm.gov.pl/sejm/term{self.term}/proceedings/{self.number}"


class Bill(Base):
    """Legislative process (projekt ustawy/uchwały), identified by its first print number."""

    __tablename__ = "bills"
    __table_args__ = (UniqueConstraint("term", "print_number"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    term: Mapped[int]
    print_number: Mapped[str] = mapped_column(String(16))  # e.g. "876"
    title: Mapped[str] = mapped_column(Text)
    document_type: Mapped[str | None] = mapped_column(String(64))  # e.g. "projekt ustawy"
    description: Mapped[str | None] = mapped_column(Text)  # official description from the Sejm API
    eli: Mapped[str | None] = mapped_column(String(64))  # set once the act is published
    isap_url: Mapped[str | None] = mapped_column(Text)
    summary: Mapped[str | None] = mapped_column(Text)  # 2 sentences generated by Gemini
    summary_model: Mapped[str | None] = mapped_column(String(64))

    votings: Mapped[list["Voting"]] = relationship(back_populates="bill")

    @property
    def source_url(self) -> str:
        return f"https://www.sejm.gov.pl/sejm{self.term}.nsf/PrzebiegProc.xsp?nr={self.print_number}"


class Voting(Base):
    __tablename__ = "votings"
    __table_args__ = (UniqueConstraint("sitting_id", "number"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    sitting_id: Mapped[int] = mapped_column(ForeignKey("sittings.id", ondelete="CASCADE"))
    bill_id: Mapped[int | None] = mapped_column(ForeignKey("bills.id", ondelete="SET NULL"))
    number: Mapped[int]
    held_at: Mapped[datetime]  # Warsaw local time, as returned by the Sejm API
    kind: Mapped[str] = mapped_column(String(32))  # ELECTRONIC / TRADITIONAL / ON_LIST
    title: Mapped[str] = mapped_column(Text)
    topic: Mapped[str | None] = mapped_column(Text)  # what exactly was voted, e.g. "poprawka 9"
    description: Mapped[str | None] = mapped_column(Text)
    is_final: Mapped[bool]  # vote on the whole bill ("całość projektu")
    yes: Mapped[int]
    no: Mapped[int]
    abstain: Mapped[int]
    not_participating: Mapped[int]
    majority_votes: Mapped[int]  # "yes" votes needed to pass

    sitting: Mapped[Sitting] = relationship(back_populates="votings")
    bill: Mapped[Bill | None] = relationship(back_populates="votings")
    clubs: Mapped[list["VotingClubResult"]] = relationship(
        back_populates="voting", order_by="VotingClubResult.club", cascade="all, delete-orphan"
    )

    @property
    def passed(self) -> bool | None:
        if self.kind != "ELECTRONIC":
            return None
        return self.yes >= self.majority_votes

    @property
    def turnout(self) -> float:
        voted = self.yes + self.no + self.abstain
        eligible = voted + self.not_participating
        return round(voted / eligible, 4) if eligible else 0.0


class VotingClubResult(Base):
    """Per-club aggregate of one voting. Individual MP votes are not stored."""

    __tablename__ = "voting_club_results"
    __table_args__ = (UniqueConstraint("voting_id", "club"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    voting_id: Mapped[int] = mapped_column(ForeignKey("votings.id", ondelete="CASCADE"))
    club: Mapped[str] = mapped_column(String(32))  # Sejm club id, e.g. "KO", "PiS"
    yes: Mapped[int] = mapped_column(default=0)
    no: Mapped[int] = mapped_column(default=0)
    abstain: Mapped[int] = mapped_column(default=0)
    absent: Mapped[int] = mapped_column(default=0)

    voting: Mapped[Voting] = relationship(back_populates="clubs")

    @property
    def position(self) -> str:
        """What most of the club's voting members did; "split" when no option got over half."""
        voted = self.yes + self.no + self.abstain
        if not voted:
            return "absent"
        for name, count in (("for", self.yes), ("against", self.no), ("abstained", self.abstain)):
            if count * 2 > voted:
                return name
        return "split"


class Layer(enum.StrEnum):
    BRONZE = "bronze"  # PDF discovered, file metadata stored
    SILVER = "silver"  # act + articles with summaries in Postgres
    GOLD = "gold"  # summary chunks embedded in Qdrant


class DocumentStatus(enum.StrEnum):
    PENDING = "pending"
    PROCESSING = "processing"
    DONE = "done"
    FAILED = "failed"


class SourceDocument(Base):
    """Tracks every PDF from the bronze folder and how far it got through the layers."""

    __tablename__ = "source_documents"

    id: Mapped[int] = mapped_column(primary_key=True)
    sha256: Mapped[str] = mapped_column(String(64), unique=True)  # same file content = same row
    file_name: Mapped[str] = mapped_column(Text)
    file_path: Mapped[str] = mapped_column(Text)
    size_bytes: Mapped[int] = mapped_column(Integer)
    page_count: Mapped[int | None] = mapped_column(Integer)
    pdf_metadata: Mapped[dict[str, Any]] = mapped_column(JSONB, default=dict)

    layer: Mapped[Layer] = mapped_column(Enum(Layer, native_enum=False), default=Layer.BRONZE)
    status: Mapped[DocumentStatus] = mapped_column(
        Enum(DocumentStatus, native_enum=False), default=DocumentStatus.PENDING
    )
    error: Mapped[str | None] = mapped_column(Text)

    act_key: Mapped[str | None] = mapped_column(String(255))
    article_count: Mapped[int | None] = mapped_column(Integer)
    unresolved_references: Mapped[int | None] = mapped_column(Integer)
    chunk_count: Mapped[int | None] = mapped_column(Integer)

    discovered_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    silver_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    gold_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
