from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    pass


class Act(Base):
    __tablename__ = "acts"

    id: Mapped[int] = mapped_column(primary_key=True)
    eli: Mapped[str] = mapped_column(String(64), unique=True)  # e.g. "DU/2024/1539"
    title: Mapped[str] = mapped_column(Text)  # full official title
    short_title: Mapped[str | None] = mapped_column(Text)  # e.g. "Kodeks karny"

    articles: Mapped[list["Article"]] = relationship(back_populates="act")


class Article(Base):
    __tablename__ = "articles"
    __table_args__ = (UniqueConstraint("act_id", "number"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    act_id: Mapped[int] = mapped_column(ForeignKey("acts.id", ondelete="CASCADE"))
    number: Mapped[str] = mapped_column(String(32))
    text: Mapped[str] = mapped_column(Text)

    act: Mapped[Act] = relationship(back_populates="articles")


class Sitting(Base):
    """Sejm sitting (posiedzenie), mirrored from /proceedings."""

    __tablename__ = "sittings"
    __table_args__ = (UniqueConstraint("term", "number"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    term: Mapped[int]
    number: Mapped[int]
    title: Mapped[str] = mapped_column(Text)
    dates: Mapped[list[date]] = mapped_column(ARRAY(Date))
    agenda: Mapped[str | None] = mapped_column(Text)  # plain-text agenda points; input for the Gemini summary
    description: Mapped[str | None] = mapped_column(Text)  # 2 sentences generated by Gemini from the agenda
    votings_count: Mapped[int] = mapped_column(default=0)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))

    @property
    def start_date(self) -> date:
        return self.dates[0]

    @property
    def end_date(self) -> date:
        return self.dates[-1]

    @property
    def status(self) -> str:
        today = date.today()
        if self.dates[0] > today:
            return "planned"
        return "finished" if self.dates[-1] < today else "in_progress"
